files = {
         #Characters
         "bf"    : ["BOYFRIEND.png", "BOYFRIEND.xml"],
         "bfcar" : ["bfCar.png", "bfCar.xml"],
         "bfxmas": ["bfChristmas.png", "bfChristmas.xml"],
         "bfpix" : ["bfPixel.png", "bfPixel.xml", "bfPixelsDEAD.png", "bfPixelsDEAD.xml"],
         "bfport": ["bfPortrait.png", "bfPortrait.xml"],
         "gf"    : ["GF_assets.png", "GF_assets.xml"],
         "gfcar" : ["gfCar.png", "gfCar.xml"],
         "gfxmas": ["gfChristmas.png", "gfChristmas.xml"],
         "gfpix" : ["gfPixel.png", "gfPixel.xml"],
         "daddy" : ["DADDY_DEAREST.png", "DADDY_DEAREST.xml"],
         "skpump": ["spooky_kids_assets.png", "spooky_kids_assets.xml"],
         "monstr": ["Monster_Assets.png", "Monster_Assets.xml"],
         "pico"  : ["Pico_FNF_assetss.png", "Pico_FNF_assetss.xml"],
         "mom"   : ["Mom_Assets.png", "Mom_Assets.xml", "momCar.png", "momCar.xml"],
         "dvxmas": ["mom_dad_christmas_assets.png", "mom_dad_christmas_assets.xml",
                     "monsterChristmas.png", "monsterChristmas.xml"],
         "senpai": ["senpai.png", "senpai.xml"],
         "spirit": ["spirit.png", "spirit.txt"],
         "spport": ["senpaiPortrait.png", "senpaiPortrait.xml", "spiritFaceForward.png",
                    "senpaiCrazy.png", "senpaiCrazy.xml"],
         #Stages
         "stage" : ["stage_light.png", "stageback.png", "stagecurtains.png", "stagefront.png"],
         "spooky": ["halloween_bg.png", "halloween_bg.xml"],
         "philly": ["behindTrain.png", "city.png", "sky.png", "street.png", "train.png",
                     "win0.png", "win1.png", "win2.png", "win3.png", "win4.png"],
         "limo"  : ["bgLimo.png", "bgLimo.xml", "dump.png", "fastCarLol.png",
                     "limoDancer.png", "limoDancer.xml", "limoDrive.png", "limoDrive.xml",
                     "limoOverlay.png", "limoSunset.png"],
         "xmas"  : ["bgEscalator.png", "bgWalls.png", "bottomBop.png", "bottomBop.xml",
                     "christmasTree.png", "christmasWall.png", "evilBG.png", "evilSnow.png",
                     "evilTree.png", "fgSnow,png", "upperBop.png", "upperBop.xml",
                     "santa.png", "santa.xml"],
         "weeb"  : ["animatedEvilSchool.png", "animatedEvilSchool.xml", "bgFreaks.png",
                     "bgFreaks.xml", "evilSchoolBG.png", "evilSchoolFG.png", "petals.png",
                     "petals.xml", "weebSchool.png", "weebSky.png", "weebStreet.png",
                     "weebTrees.png", "weebTrees.xml", "weebTreesBack.png"],
         #UI
         "icons" : ["iconGrid.png"],
         "title" : ["gfDanceTitle.png", "gfDanceTitle.xml", "logo.png"],
         "bumpin": ["logoBumpin.png", "logoBumpin.xml"],
         "menu"  : ["FNF_main_menu_assets.png", "FNF_main_menu_assets.xml",
                    "menuBG.png", "menuBGBlue.png", "menuBGMagenta.png", "menuDesat.png"],
         "grades": ["bad.png", "combo.png", "good.png", "grafix.png", "shit.png", "sick.png"],
         "nums"  : ["num0.png", "num1.png", "num2.png", "num3.png", "num4.png", "num5.png",
                     "num6.png", "num7,png", "num8.png", "num9.png"],
         "genui" : ["go.png", "ready.png", "restart.png", "set.png", "lose.png", "lose.xml",
                     "healthBar.png", "backspace.png", "backspace.xml", "NOTE_assets.png",
                     "NOTE_assets.xml", "speech_bubble_talking.png", "speech_bubble_talking.xml"],
         "genui2": ["alphabet.png", "alphabet.xml", "newgrounds_logo.png",
                     "titleEnter.png", "titleEnter.xml"],
         "pixui" : ["arrowEnds.png", "arrows-pixels.png", "bad-pixel.png", "combo-pixel.png",
                     "date-pixel.png", "dialogueBox-evil.png", "dialogueBox-evil.xml",
                     "dialogueBox-pixel.png", "dialogueBox-pixel.xml", "dialogueBox-senpaiMad.png",
                     "dialogueBox-senpaiMad.xml", "good-pixel.png", "hand_textbox.png",
                     "num0-pixel.png", "num1-pixel.png", "num2-pixel.png", "num3-pixel.png",
                     "num4-pixel.png", "num5-pixel.png", "num6-pixel.png", "num7-pixel.png",
                     "num8-pixel.png", "num9-pixel.png", "ready-pixel.png", "set-pixel.png",
                     "shit-pixel.png", "sick-pixel.png"],
         "campui": ["campaign_menu_UI_assets.png", "campaign_menu_UI_assets.xml",
                     "campaign_menu_UI_characters.png", "campaign_menu_UI_characters.xml"],
         "useles": ["lol.png", "screencapTierImage.png", "zzzzzzzz.png"],
         "pasalt": ["bfLol.png", "bfLol.xml", "pauseBG.png", "pauseUI.png", "pauseUI.xml"],
         #Sounds
         "music" : ["breakfast.ogg", "gameOver.ogg", "gameOverEnd.ogg"],
         "muspix": ["gameOver-pixel.ogg", "gameOverEnd-pixel.ogg", "Lunchbox.ogg",
                     "LunchboxScary.ogg"],
         "train" : ["train_passes.ogg"],
         "sounds": ["ANGRY.ogg", "ANGER_TEXT_BOX.ogg", "badnoise1.ogg", "badnoise2.ogg",
                     "badnoise3.ogg", "carPass0.ogg", "carPass1.ogg", "clickText.ogg",
                     "fnf_loss_sfx.ogg", "fnf_loss_sfx-pixel.ogg", "freshIntro.ogg",
                     "GF_1.ogg", "GF_2.ogg", "GF_3.ogg", "GF_4.ogg", "intro1.ogg",
                     "intro1-pixel.ogg", "intro2.ogg", "intro2-pixel.ogg", "intro3.ogg",
                     "intro3-pixel.ogg", "introGo.ogg", "introGo-pixel.ogg",
                     "Lights_Shut_off.ogg", "Lights_Turn_On.ogg", "missnote1.ogg", "missnote2.ogg",
                     "missnote3.ogg", "pixelText.ogg", "Senpai_Dies.ogg", "soundTest.ogg",
                     "thunder_1.ogg", "thunder_2.ogg"],
         #["cancelMenu.ogg", "confirmMenu.ogg", "scrollMenu.ogg"],
        }
filenames = list(files.keys())

formats = [   # 0 - Funkin Standard
           {
            #Characters
            "bf"    : "/images/",
            "bfcar" : "/images/",
            "bfxmas": "/images/christmas/",
            "bfpix" : "/images/weeb/",
            "bfport": "/images/weeb/",
            "gf"    : "/images/",
            "gfcar" : "/images/",             "gfxmas": "/images/christmas/",
            "gfpix" : "/images/weeb/",
            "daddy" : "/images/",
            "skpump": "/images/",
            "monstr": "/images/",
            "pico"  : "/images/",
            "mom"   : "/images/",
            "dvxmas": "/images/christmas/",
            "senpai": "/images/weeb/",
            "spirit": "/images/weeb/",
            "spport": "/images/weeb/",
            #Stages
            "stage" : "/images/",
            "spooky": "/images/",
            "philly": "/images/philly/",
            "limo"  : "/images/limo/",
            "xmas"  : "/images/christmas/",
            "weeb"  : "/images/weeb/",
            #UI
            "icons" : "/images/",
            "title" : "/images/",
            "bumpin": "/images/",
            "menu"  : "/images/",
            "grades": "/images/",
            "nums"  : "/images/",
            "genui" : "/images/",
            "genui2": "/images/",
            "pixui" : "/images/weeb/pixelUI/",
            "campui": "/images/",
            "useles": "/images/",
            "pasalt": "/images/pauseAlt/",
            #Sounds
            "music" : "/music/",
            "muspix": "/music/",
            "train" : "/sounds/",
            "sounds": "/sounds/",
           },
           # 1 - Kade Old
           {
            #Characters
            "bf"    : "/shared/images/",
            "bfcar" : "/week4/images/",
            "bfxmas": "/week5/images/christmas/",
            "bfpix" : "/week6/images/weeb/",
            "bfport": "/week6/images/weeb/",
            "gf"    : "/shared/images/",
            "gfcar" : "/week4/images/",
            "gfxmas": "/week5/images/christmas/",
            "gfpix" : "/week6/images/weeb/",
            "daddy" : "/shared/images/",
            "skpump": "/week2/images/",
            "monstr": "/week2/images/",
            "pico"  : "/week3/images/",
            "mom"   : "/week4/images/",
            "dvxmas": "/week5/images/christmas/",
            "senpai": "/week6/images/weeb/",
            "spirit": "/week6/images/weeb/",
            "spport": "/week6/images/weeb/",
            #Stages
            "stage" : "/shared/images/",
            "spooky": "/week2/images/",
            "philly": "/week3/images/philly/",
            "limo"  : "/week4/images/limo/",
            "xmas"  : "/week5/images/christmas/",
            "weeb"  : "/week6/images/weeb/",
            #UI
            "icons" : "/shared/images/",
            "title" : "/images/",
            "bumpin": "/images/",
            "menu"  : "/images/",
            "grades": "shared//images/",
            "nums"  : "/images/",
            "genui" : "/shared/images/",
            "genui2": "/images/",
            "pixui" : "/week6/images/weeb/pixelUI/",
            "campui": "/images/",
            "useles": "/shared/images/",
            "pasalt": "/images/pauseAlt/",
            #Sounds
            "music" : "/shared/music/",
            "muspix": "/week6/music/",
            "train" : "/shared/sounds/",
            "sounds": "/shared/sounds/",
           },
           # 2 - Kade New
           {
            #Characters
            "bf"    : "/shared/images/characters/",
            "bfcar" : "/shared/images/characters/",
            "bfxmas": "/shared/images/characters/",
            "bfpix" : "/shared/images/characters/",
            "bfport": "/week6/images/weeb/",
            "gf"    : "/shared/images/characters/",
            "gfcar" : "/shared/images/characters/",
            "gfxmas": "/shared/images/characters/",
            "gfpix" : "/shared/images/characters/",
            "daddy" : "/shared/images/characters/",
            "skpump": "/shared/images/characters/",
            "monstr": "/shared/images/characters/",
            "pico"  : "/shared/images/characters/",
            "mom"   : "/shared/images/characters/",
            "dvxmas": "/shared/images/characters/",
            "senpai": "/shared/images/characters/",
            "spirit": "/shared/images/characters/",
            "spport": "/week6/images/weeb/",
            #Stages
            "stage" : "/shared/images/",
            "spooky": "/week2/images/",
            "philly": "/week3/images/philly/",
            "limo"  : "/week4/images/limo/",
            "xmas"  : "/week5/images/christmas/",
            "weeb"  : "/week6/images/weeb/",
            #UI
            "icons" : "/images/",
            "title" : "/images/",
            "bumpin": "/images/",
            "menu"  : "/images/",
            "grades": "/shared/images/",
            "nums"  : "/images/",
            "genui" : "/shared/images/",
            "genui2": "/images/",
            "pixui" : "/week6/images/weeb/pixelUI/",
            "campui": "/images/",
            "useles": "/shared/images/",
            "pasalt": "/shared/images/pauseAlt/",
            #Sounds
            "music" : "/shared/music/",
            "muspix": "/week6/music/",
            "train" : "/week3/sounds/",
            "sounds": "/shared/sounds/",
           }
          ]
    
music = [
         {
          "BlammedInst" : "/music/Blammed_Inst.ogg",
          "BlammedVoic" : "/music/Blammed_Voices.ogg",
          "BopeeboInst" : "/music/Bopeebo_Inst.ogg",
          "BopeeboVoic" : "/music/Bopeebo_Voices.ogg",
          "CocoaInst"   : "/music/Cocoa_Inst.ogg",
          "CocoaVoic"   : "/music/Cocoa_Voices.ogg",
          "DadbatInst"  : "/music/Dadbattle_Inst.ogg",
          "DadbatVoic"  : "/music/Dadbattle_Voices.ogg",
          "EggnogInst"  : "/music/Eggnog_Inst.ogg",
          "EggnogVoic"  : "/music/Eggnog_Voices.ogg",
          "FreshInst"   : "/music/Fresh_Inst.ogg",
          "FreshVoic"   : "/music/Fresh_Voices.ogg",
          "HighInst"    : "/music/High_Inst.ogg",
          "HighVoic"    : "/music/High_Voices.ogg",
          "MilfInst"    : "/music/Milf_Inst.ogg",
          "MilfVoic"    : "/music/Milf_Voices.ogg",
          "MonsterInst" : "/music/Monster_Inst.ogg",
          "MonsterVoic" : "/music/Monster_Voices.ogg",
          "PhillyInst"  : "/music/Philly_Inst.ogg",
          "PhillyVoic"  : "/music/Philly_Voices.ogg",
          "PicoInst"    : "/music/Pico_Inst.ogg",
          "PicoVoic"    : "/music/Pico_Voices.ogg",
          "RosesInst"   : "/music/Roses_Inst.ogg",
          "RosesVoic"   : "/music/Roses_Voices.ogg",
          "SatinInst"   : "/music/Satin-Panties_Inst.ogg",
          "SatinVoic"   : "/music/Satin-Panties_Voices.ogg",
          "SenpaiInst"  : "/music/Senpai_Inst.ogg",
          "SenpaiVoic"  : "/music/Senpai_Voices.ogg",
          "SouthInst"   : "/music/South_Inst.ogg",
          "SouthVoic"   : "/music/South_Voices.ogg",
          "SpookezInst" : "/music/Spookeez_Inst.ogg",
          "SpookezVoic" : "/music/Spookeez_Voices.ogg",
          "TestInst"    : "/music/Test_Inst.ogg",
          "TestVoic"    : "/music/Test_Voices.ogg",
          "ThornsInst"  : "/music/Thorns_Inst.ogg",
          "ThornsVoic"  : "/music/Thorns_Voices.ogg",
          "Tutorial"    : "/music/Tutorial_Inst.ogg",
          "WinterInst"  : "/music/Winter-Horrorland_Inst.ogg",
          "WinterVoic"  : "/music/Winter-Horrorland_Voices.ogg",
          "freakyMenu"  : "/music/freakyMenu.ogg",
         },
         {
          "BlammedInst" : "/song/blammed/Inst.ogg",
          "BlammedVoic" : "/song/blammed/Voices.ogg",
          "BopeeboInst" : "/song/bopeebo/Inst.ogg",
          "BopeeboVoic" : "/song/bopeebo/Voices.ogg",
          "CocoaInst"   : "/song/cocoa/Inst.ogg",
          "CocoaVoic"   : "/song/cocoa/Voices.ogg",
          "DadbatInst"  : "/song/dadbattle/Inst.ogg",
          "DadbatVoic"  : "/song/dadbattle/Voices.ogg",
          "EggnogInst"  : "/song/eggnog/Inst.ogg",
          "EggnogVoic"  : "/song/eggnog/Voices.ogg",
          "FreshInst"   : "/song/fresh/Inst.ogg",
          "FreshVoic"   : "/song/fresh/Voices.ogg",
          "HighInst"    : "/song/high/Inst.ogg",
          "HighVoic"    : "/song/high/Voices.ogg",
          "MilfInst"    : "/song/milf/Inst.ogg",
          "MilfVoic"    : "/song/milf/Voices.ogg",
          "MonsterInst" : "/song/monster/Inst.ogg",
          "MonsterVoic" : "/song/monster/Voices.ogg",
          "PhillyInst"  : "/song/philly/Inst.ogg",
          "PhillyVoic"  : "/song/philly/Voices.ogg",
          "PicoInst"    : "/song/pico/Inst.ogg",
          "PicoVoic"    : "/song/pico/Voices.ogg",
          "RosesInst"   : "/song/roses/Inst.ogg",
          "RosesVoic"   : "/song/roses/Voices.ogg",
          "SatinInst"   : "/song/satin-panties/Inst.ogg",
          "SatinVoic"   : "/song/satin-panties/Voices.ogg",
          "SenpaiInst"  : "/song/senpai/Inst.ogg",
          "SenpaiVoic"  : "/song/senpai/Voices.ogg",
          "SouthInst"   : "/song/south/Inst.ogg",
          "SouthVoic"   : "/song/south/Voices.ogg",
          "SpookezInst" : "/song/spookeez/Inst.ogg",
          "SpookezVoic" : "/song/spookeez/Voices.ogg",
          "TestInst"    : "/song/test/Inst.ogg",
          "TestVoic"    : "/song/test/Voices.ogg",
          "ThornsInst"  : "/song/thorns/Inst.ogg",
          "ThornsVoic"  : "/song/thorns/Voices.ogg",
          "Tutorial"    : "/song/tutorial/Inst.ogg",
          "WinterInst"  : "/song/winter-horrorland/Inst.ogg",
          "WinterVoic"  : "/song/winter-horrorland/Voices.ogg",
          "freakyMenu"  : "/music/freakyMenu.ogg",
         },
         {
          "BlammedInst" : "/song/blammed/Inst.ogg",
          "BlammedVoic" : "/song/blammed/Voices.ogg",
          "BopeeboInst" : "/song/bopeebo/Inst.ogg",
          "BopeeboVoic" : "/song/bopeebo/Voices.ogg",
          "CocoaInst"   : "/song/cocoa/Inst.ogg",
          "CocoaVoic"   : "/song/cocoa/Voices.ogg",
          "DadbatInst"  : "/song/dadbattle/Inst.ogg",
          "DadbatVoic"  : "/song/dadbattle/Voices.ogg",
          "EggnogInst"  : "/song/eggnog/Inst.ogg",
          "EggnogVoic"  : "/song/eggnog/Voices.ogg",
          "FreshInst"   : "/song/fresh/Inst.ogg",
          "FreshVoic"   : "/song/fresh/Voices.ogg",
          "HighInst"    : "/song/high/Inst.ogg",
          "HighVoic"    : "/song/high/Voices.ogg",
          "MilfInst"    : "/song/milf/Inst.ogg",
          "MilfVoic"    : "/song/milf/Voices.ogg",
          "MonsterInst" : "/song/monster/Inst.ogg",
          "MonsterVoic" : "/song/monster/Voices.ogg",
          "PhillyInst"  : "/song/philly/Inst.ogg",
          "PhillyVoic"  : "/song/philly/Voices.ogg",
          "PicoInst"    : "/song/pico/Inst.ogg",
          "PicoVoic"    : "/song/pico/Voices.ogg",
          "RosesInst"   : "/song/roses/Inst.ogg",
          "RosesVoic"   : "/song/roses/Voices.ogg",
          "SatinInst"   : "/song/satin-panties/Inst.ogg",
          "SatinVoic"   : "/song/satin-panties/Voices.ogg",
          "SenpaiInst"  : "/song/senpai/Inst.ogg",
          "SenpaiVoic"  : "/song/senpai/Voices.ogg",
          "SouthInst"   : "/song/south/Inst.ogg",
          "SouthVoic"   : "/song/south/Voices.ogg",
          "SpookezInst" : "/song/spookeez/Inst.ogg",
          "SpookezVoic" : "/song/spookeez/Voices.ogg",
          "TestInst"    : "/song/test/Inst.ogg",
          "TestVoic"    : "/song/test/Voices.ogg",
          "ThornsInst"  : "/song/thorns/Inst.ogg",
          "ThornsVoic"  : "/song/thorns/Voices.ogg",
          "Tutorial"    : "/song/tutorial/Inst.ogg",
          "WinterInst"  : "/song/winter-horrorland/Inst.ogg",
          "WinterVoic"  : "/song/winter-horrorland/Voices.ogg",
          "freakyMenu"  : "/music/freakyMenu.ogg",
         }
        ]